myproject/urls.py
from django.conf.urls import patterns, include, url
from myproject.core.views import *

from django.contrib import admin

urlpatterns = patterns(
    'myproject.core.views',
    url(r'^$', 'home', name='home'),
    url(r'^persons/$', PersonList.as_view(), name='person_list'),
    url(r'^occupations/$', OccupationList.as_view(), name='occupation_list'),
    url(r'^persons/(?P<pk>\d+)/$',
        PersonDetail.as_view(), name='person_detail'),
    url(r'^products/$', ProductList.as_view(), name='product_list'),
    url(r'^products/(?P<pk>\d+)/$',
        ProductDetail.as_view(), name='product_detail'),
    url(r'^brands/$', BrandList.as_view(), name='brand_list'),
    url(r'^categorys/$', CategoryList.as_view(), name='category_list'),

    url(r'^person/add/$', PersonCreate.as_view(), name='person_add'),
    url(r'^occupation/add/$', OccupationCreate.as_view(),
        name='occupation_add'),
    url(r'^address/add/$', AddressCreate.as_view(), name='address_add'),
    url(r'^phone/add/$', PhoneCreate.as_view(), name='phone_add'),
    url(r'^product/add/$', ProductCreate.as_view(), name='product_add'),
    url(r'^brand/add/$', BrandCreate.as_view(), name='brand_add'),
    url(r'^category/add/$', CategoryCreate.as_view(), name='category_add'),

    url(r'^download/$', 'download', name='download'),
    url(r'^about/$', 'about', name='about'),
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^admin/', include(admin.site.urls), name='admin'),
)

myproject/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.formats import number_format
# List of values for use in choices
from .applib.lists import gender_list, treatment_list, type_address_list, uf_list, type_phone_list


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(
        _('criado em'), auto_now_add=True, auto_now=False)
    modified_at = models.DateTimeField(
        _('modificado em'), auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel):
    gender = models.CharField(_(u'gênero'), max_length=1, choices=gender_list)
    treatment = models.CharField(
        _('tratamento'), max_length=4, choices=treatment_list)
    first_name = models.CharField(_('nome'), max_length=30)
    last_name = models.CharField(_('sobrenome'), max_length=30)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    birthday = models.DateTimeField(_('nascimento'))
    email = models.EmailField(_('e-mail'))
    occupation = models.ForeignKey(
        "Occupation", verbose_name=_(u'profissão'))
    active = models.BooleanField(_('ativo'), default=True)
    blocked = models.BooleanField(_('bloqueado'), default=False)

    class Meta:
        ordering = ['first_name']
        verbose_name = "pessoa"
        verbose_name_plural = "pessoas"

    def __str__(self):
        return u"%s %s" % (self.first_name, self.last_name)

    full_name = property(__str__)

    def get_person_detail_url(self):
        return u"/persons/%i" % self.id


class Occupation(models.Model):
    occupation = models.CharField(_(u'Profissão'), max_length=30)

    class Meta:
        ordering = ['occupation']
        verbose_name = u"profissão"
        verbose_name_plural = u"profissões"

    def __str__(self):
        return self.occupation


class Address(models.Model):
    type_address = models.CharField(
        _(u'tipo de endereço'), max_length=1, choices=type_address_list, default='i')
    address = models.CharField(_(u'endereço'), max_length=80)
    address_number = models.PositiveIntegerField(_(u'número'))
    complement = models.CharField(_('complemento'), max_length=80, blank=True)
    district = models.CharField(_('bairro'), max_length=80)
    city = models.CharField(_('cidade'), max_length=80)
    uf = models.CharField(_('UF'), max_length=2, choices=uf_list)
    cep = models.CharField(_('CEP'), max_length=9)
    person = models.ForeignKey(
        "Person", verbose_name=_('pessoa'), related_name='pessoa_endereco')

    class Meta:
        verbose_name = u"endereço"
        verbose_name_plural = u"endereços"

    def __str__(self):
        return self.cep


class Phone(models.Model):
    person = models.ForeignKey(
        "Person", verbose_name=_('pessoa'), related_name='pessoa_fone')
    phone = models.CharField(_('telefone'), max_length=20)
    type_phone = models.CharField(
        _('tipo de telefone'), max_length=3, choices=type_phone_list, default='pri')

    class Meta:
        verbose_name = "telefone"
        verbose_name_plural = "telefones"

    def __str__(self):
        return self.phone


class Brand(models.Model):
    brand = models.CharField(_('marca'), max_length=30)

    class Meta:
        ordering = ['brand']
        verbose_name = "marca"
        verbose_name_plural = "marcas"

    def __str__(self):
        return self.brand


class Category(models.Model):
    category = models.CharField(_('categoria'), max_length=30)

    class Meta:
        ordering = ['category']
        verbose_name = "categoria"
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.category


class Product(TimeStampedModel):
    imported = models.BooleanField(_('importado'), default=False)
    outofline = models.BooleanField(_('fora de linha'), default=False)
    ncm = models.CharField(_('NCM'), max_length=8)
    category = models.ForeignKey(
        "Category", verbose_name='categoria', related_name='categoria')
    brand = models.ForeignKey(
        "Brand", verbose_name='marca', related_name='marca')
    product = models.CharField(_('produto'), max_length=80, unique=True)
    cost = models.DecimalField(_('custo'), max_digits=8, decimal_places=2)
    icms = models.DecimalField(_('ICMS'), max_digits=3, decimal_places=2)
    ipi = models.DecimalField(_('IPI'), max_digits=3, decimal_places=2)
    stock = models.PositiveIntegerField(_('estoque atual'))
    stock_min = models.PositiveIntegerField(_(u'estoque mínimo'), default=0)

    class Meta:
        ordering = ['product']
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.product

    def get_product_detail_url(self):
        return u"/products/%i" % self.id

    def get_cost(self):
        return u"R$ %s" % number_format(self.cost, 2)

    def get_icms(self):
        return u"%s" % number_format(self.icms * 100, 0)

    def get_ipi(self):
        return u"%s" % number_format(self.ipi * 100, 0)

myproject/core/forms.py
from django.forms import ModelForm
from .models import Person, Occupation, Address, Phone, Product, Brand, Category


class PersonForm(ModelForm):

    class Meta:
        model = Person
        fields = '__all__'


class OccupationForm(ModelForm):

    class Meta:
        model = Occupation
        fields = '__all__'


class AddressForm(ModelForm):

    class Meta:
        model = Address
        fields = '__all__'


class PhoneForm(ModelForm):

    class Meta:
        model = Phone
        fields = '__all__'


class ProductForm(ModelForm):

    class Meta:
        model = Product
        fields = '__all__'


class BrandForm(ModelForm):

    class Meta:
        model = Brand
        fields = '__all__'


class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

myproject/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, DetailView
from django.core.urlresolvers import reverse_lazy
from .models import Person, Occupation, Address, Phone, Product, Brand, Category


def home(request):
    return render(request, 'index.html')


class PersonList(ListView):
    template_name = 'core/person/person_list.html'
    model = Person
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(PersonList, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        context['name'] = 'pessoa'
        context['name_plural'] = 'pessoas'
        return context

    def get_queryset(self):
        persons = Person.objects.all()
        var_get_search = self.request.GET.get('search_box')
        if var_get_search is not None:
            persons = persons.filter(first_name__icontains=var_get_search)
        return persons


class PersonDetail(DetailView):
    template_name = 'core/person/person_detail.html'
    model = Person

    def get_context_data(self, **kwargs):
        context = super(PersonDetail, self).get_context_data(**kwargs)
        person = Person.objects.get(pk=self.kwargs['pk'])
        context['phones'] = Phone.objects.all().filter(
            person_id=person)
        context['address'] = Address.objects.all().filter(
            person_id=person)
        return context


class PersonCreate(CreateView):
    template_name = 'core/person/person_create_form.html'
    model = Person
    success_url = reverse_lazy('person_list')

    def get_context_data(self, **kwargs):
        context = super(PersonCreate, self).get_context_data(**kwargs)
        context['name'] = 'pessoa'
        return context


class OccupationList(ListView):
    template_name = 'core/person/occupation_list.html'
    model = Occupation
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(OccupationList, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        context['name'] = u'profissão'
        context['name_plural'] = u'profissões'
        return context

    def get_queryset(self):
        occupations = Occupation.objects.all()
        var_get_search = self.request.GET.get('search_box')
        if var_get_search is not None:
            occupations = occupations.filter(
                occupation__icontains=var_get_search)
        return occupations


class OccupationCreate(CreateView):
    template_name = 'core/person/occupation_create_form.html'
    model = Occupation
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(OccupationCreate, self).get_context_data(**kwargs)
        context['name'] = u'profissão'
        return context


class AddressCreate(CreateView):
    template_name = 'core/person/address_create_form.html'
    model = Address
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(AddressCreate, self).get_context_data(**kwargs)
        context['name'] = u'endereço'
        return context


class PhoneCreate(CreateView):
    template_name = 'core/person/phone_create_form.html'
    model = Phone
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(PhoneCreate, self).get_context_data(**kwargs)
        context['name'] = 'telefone'
        return context


class ProductList(ListView):
    template_name = 'core/product/product_list.html'
    model = Product
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        context['name'] = 'produto'
        context['name_plural'] = 'produtos'
        return context

    def get_queryset(self):
        products = Product.objects.all()
        var_get_search = self.request.GET.get('search_box')
        if var_get_search is not None:
            products = products.filter(product__icontains=var_get_search)
        return products


class ProductDetail(DetailView):
    template_name = 'core/product/product_detail.html'
    model = Product


class ProductCreate(CreateView):
    template_name = 'core/product/product_create_form.html'
    model = Product
    success_url = reverse_lazy('product_list')

    def get_context_data(self, **kwargs):
        context = super(ProductCreate, self).get_context_data(**kwargs)
        context['name'] = 'produto'
        return context


class BrandList(ListView):
    template_name = 'core/product/brand_list.html'
    model = Brand
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(BrandList, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        context['name'] = 'marca'
        context['name_plural'] = 'marcas'
        return context

    def get_queryset(self):
        brands = Brand.objects.all()
        var_get_search = self.request.GET.get('search_box')
        if var_get_search is not None:
            brands = brands.filter(brand__icontains=var_get_search)
        return brands


class BrandCreate(CreateView):
    template_name = 'core/product/brand_create_form.html'
    model = Brand
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(BrandCreate, self).get_context_data(**kwargs)
        context['name'] = 'marca'
        return context


class CategoryList(ListView):
    template_name = 'core/product/category_list.html'
    model = Category
    paginate_by = 23

    def get_context_data(self, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        context['name'] = 'categoria'
        context['name_plural'] = 'categorias'
        return context

    def get_queryset(self):
        categorys = Category.objects.all()
        var_get_search = self.request.GET.get('search_box')
        if var_get_search is not None:
            categorys = categorys.filter(category__icontains=var_get_search)
        return categorys


class CategoryCreate(CreateView):
    template_name = 'core/product/category_create_form.html'
    model = Category
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(CategoryCreate, self).get_context_data(**kwargs)
        context['name'] = 'categoria'
        return context


def download(request):
    return render(request, 'download.html')


def contact(request):
    return render(request, 'contact.html')


def about(request):
    return render(request, 'about.html')

myproject/core/templates/core/person/address_create_form.html
{% extends "base_create_form.html" %}

{% block title %}
    <title>Address Form</title>
{% endblock title %}

myproject/core/templates/core/person/occupation_create_form.html
{% extends "base_create_form.html" %}

{% block title %}
    <title>Occupation Form</title>
{% endblock title %}

myproject/core/templates/core/person/occupation_list.html
{% extends "base.html" %}

{% block title %}
    <title>Occupation List</title>
{% endblock title %}

{% block content %}
    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
        <a href="{% url 'occupation_add' %}">
            <button id="new_sale" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
        </a>
        <!-- search form -->
        <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>

    <h1>Lista de {{ name_plural.capitalize }}</h1>

    <div>
        {% if occupation_list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Profissão</th>
                    </tr>
                </thead>
                <tbody>
                {% for occupation in occupation_list %}
                    <tr>
                        <td>{{ occupation.occupation }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="lead text-danger">Sem itens na lista.</p>
        {% endif %}
    </div>

    <hr>
    <div>
        <h3><b>Total:</b> {{ count }}
            {% if count <= 1 %}
                {{ name }}
            {% else %}
                {{ name_plural }}
            {% endif %}
        </h3>
    </div>

<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}

myproject/core/templates/core/person/person_create_form.html
{% extends "base_create_form.html" %}

{% block title %}
    <title>Person Form</title>
{% endblock title %}

myproject/core/templates/core/person/person_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Person Detail</title>
{% endblock title %}

{% block content %}

<div class="col-lg-8">
	<div class="col-md-2 column">
		<img data-src="holder.js/120x120" class="img-square" />
	</div>
	<div class="col-md-offset-3 column">
		<h1>{{ object.full_name }}, {{ object.get_treatment_display }}</h1>
		<h2>{{ object.occupation }}</h2>
		<h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
	</div>

	</br>

    <table class="table table-user-information">
  		<tbody>
	      <tr>
	        <th class="col-md-3 text-right">Sexo</th>
	        <td>{{ object.get_gender_display }}</td>
	      </tr>
	      <tr>
	        <th class="col-md-3 text-right">CPF</th>
	        <td>{{ object.cpf }}</td>
	      </tr>
	      <tr>
	        <th class="col-md-3 text-right">Nascimento</th>
	        <td>{{ object.birthday }}</td>
	      </tr>
	      <tr>
	        <th class="col-md-3 text-right">Ativo</th>
	        <td>
		        {% if object.active %}
		            <span class="glyphicon glyphicon-ok-sign" style="color: #44AD41"></span>
		        {% else %}
		            <span class="glyphicon glyphicon-minus-sign" style="color: #DE2121"></span>
		        {% endif %}
			</td>
	      </tr>
	      <tr>
	        <th class="col-md-3 text-right">Bloqueado</th>
	        <td>
		        {% if object.blocked %}
		            <span class="glyphicon glyphicon-ok-sign" style="color: #44AD41"></span>
		        {% else %}
		            <span class="glyphicon glyphicon-minus-sign" style="color: #DE2121"></span>
		        {% endif %}
			</td>
	      </tr>
        </tbody>
    </table>

	{% if phones %}
		<h3>Telefones</h3>

		<div class="clearfix">
			<ul class="list-group col-xs-6">
				{% for phone in phones %}
				  <li class="list-group-item">
				    <span class="col-md-6 text-right">{{ phone.phone }}</span>
				    <span>{{ phone.get_type_phone_display }}</span>
				  </li>
				{% endfor %}
			</ul>
		</div>
	{% endif %}

	{% if address %}
		<h3>Endereço</h3>
		<hr>

		{% for address in address %}
		  <p><strong>{{ address.get_type_address_display }}</strong></p>
	    	<p>{{ address.address }}, {{ address.address_number }}</p>
	        <p>{{ address.complement }}</p>
	        <p><b>Bairro:</b> {{ address.district }}</p>
	        <p><b>Cidade/UF:</b> {{ address.city }} - {{ address.uf }}</p>
	        <p><b>CEP:</b> {{ address.cep }}</p>
	        <hr>
		{% endfor %}
	{% endif %}

</div>

{% endblock content %}

myproject/core/templates/core/person/person_list.html
{% extends "base.html" %}

{% block title %}
    <title>Person List</title>
{% endblock title %}

{% block content %}
    <form class="navbar-form navbar-right" action="." method="get">
        <!-- add -->
        <a href="{% url 'person_add' %}">
            <button id="new_sale" type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </button>
        </a>
        <!-- search form -->
        <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>

    <h1>Lista de {{ name_plural.capitalize }} <font size="3">(Nomes fictícios)</font></h1>

    <div>
        {% if person_list %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Email</th>
                        <th>Nascimento</th>
                        <th>Profissão</th>
                        <th>Ativo</th>
                    </tr>
                </thead>
                <tbody>
                {% for person in person_list %}
                    <tr>
                        <td><a href="{{ person.get_person_detail_url }}">{{ person.full_name }}, {{ person.get_treatment_display }}</a></td>
                        <td>{{ person.cpf }}</td>
                        <td>{{ person.email }}</td>
                        <td>{{ person.birthday|date:"d/m/Y" }}</td>
                        <td>{{ person.occupation }}</td>
                        
                        <td class="text-center">
                            {% if person.active %}
                                <span class="glyphicon glyphicon-ok-sign" style="color: #44AD41"></span>
                            {% else %}
                                <span class="glyphicon glyphicon-minus-sign" style="color: #DE2121"></span>
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="lead text-danger">Sem itens na lista.</p>
        {% endif %}
    </div>

    <hr>
    <div>
        <h3><b>Total:</b> {{ count }}
            {% if count <= 1 %}
                {{ name }}
            {% else %}
                {{ name_plural }}
            {% endif %}
        </h3>
    </div>


<!-- pagination -->
{% include "pagination.html" %}

{% endblock content %}

myproject/core/templates/core/person/phone_create_form.html
{% extends "base_create_form.html" %}

{% block title %}
    <title>Phone Form</title>
{% endblock title %}